require 'polish_validators/version'
require 'polish_validators/nip_validator'
require 'polish_validators/pesel_validator'
require 'polish_validators/regon_validator'
require 'polish_validators/iban_validator'
